package enums;

public enum CVMETHOD {
    OFFLINE_PLAINTEXT_PIN,
    ONLINE_PIN,
    OFFLINE_PLAINTEXT_PIN_AND_SIGNATURE,
    OFFLINE_ENCIPHERED_PIN,
    OFFLINE_ENCIPHERED_PIN_AND_SIGNATURE,
    SIGNATURE,
    NO_CVM_PERFORMED
}
