name: Publish package to GitHub Packages enkpay
on:
  push:
    branches:
      - main  # Adjust this based on your branch name

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Configure settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>ebukamiracle35@gmail.com</username><password>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</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Publish package
        run: mvn --batch-mode deploy

